Fix K8S-Proxy image build and tag
bitwarden/server pull request #1349
Opened 2021-05-25 15:31 UTC by vgrassia

K8S-Proxy Docker image was actually using the NGINX image due to a typo.  This correct the issue.

2021-05-26 15:01 UTC, joseph-flinn requested changes

2021-05-26 15:04 UTC, joseph-flinn requested changes

2021-05-26 15:04 UTC, joseph-flinn commented on .github/workflows/release.yml
> -      - name: Make docker stub
This should only run once (not in the matrix)

2021-05-26 15:04 UTC, joseph-flinn commented on .github/workflows/release.yml
> +      - name: Upload Docker stub artifact
This should only run once (not in the matrix)

2021-05-26 15:04 UTC, joseph-flinn commented on .github/workflows/release.yml
> +      - name: Build Swagger
This should only run once (no in the matrix)

2021-05-26 15:04 UTC, joseph-flinn commented on .github/workflows/release.yml
> +      - name: Upload Swagger artifact
This should only run once (no in the matrix)

2021-05-26 16:01 UTC, vgrassia commented on .github/workflows/release.yml
> +        service_name: [
Array's are supported directly in the YAML spec; they are just called `sequences`. It's supported in block format (with '-' characters) or between square brackets.  I could switch it to something like below, let me know what you think:

```
- admin
- api
- attachments
- ...
```

2021-05-26 16:43 UTC, joseph-flinn approved these changes

2021-05-27 14:31 UTC, joseph-flinn approved these changes

2021-05-27 14:32 UTC, merged