Add Stripe Adapter and add IBraintreeGateway to DI
bitwarden/server pull request #1596
Opened 2021-09-24 12:32 UTC by Hinton

## Objective
In an effort to make the `StripePaymentService` testable, I've refactored the third party logic to be injected as dependencies which can be mocked during testing.

To achive this I had to add a wrapper to stripe, and add a new DI provider for IBraintreeGateway.

2021-09-24 14:39 UTC, MGibson1 submitted a review, later dismissed
Nice!

2021-09-24 22:37 UTC, justindbaur commented on src/Core/Utilities/ServiceCollectionExtensions.cs
> +            services.AddSingleton<Braintree.IBraintreeGateway>((serviceProvider) =>
I had discussed the possibility of doing this on #1454. I think this is a really good idea!

2021-09-27 21:00 UTC, MGibson1 approved these changes

2021-09-27 21:01 UTC, merged

2021-09-27 21:02 UTC, MGibson1 requested changes
Unfortunately `SubscriptionUpdate` uses Stripe. We should probably make it use the adapter.

To me that also means that a static factory is preferrable. I'll leave up to you, though

2021-09-28 07:56 UTC, Hinton commented
@MGibson1 `SubscriptionUpdate` only extends the business data model right? Which doesn't need to be mocked.

2021-09-28 11:48 UTC, MGibson1 commented
yeah, you're right, there are no services in there.