Bumping the self-host versions
bitwarden/server pull request #1762
Opened 2021-12-14 14:13 UTC by joseph-flinn

## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective
Bump the self-host version to the latest released.

## Code changes
* **./scripts/bitwarden.sh:** Bump server version 1.45.0 and web 2.25.0
* * **./scripts/bitwarden.ps1:** Bump server version 1.45.0 and web 2.25.0

## Before you submit
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-12-14 17:29 UTC, cscharf approved these changes

2021-12-14 18:38 UTC, haneef95 commented
How comes the version numbers are mismatching with the tag, e.g.:
https://github.com/bitwarden/server/blob/v1.45.1/scripts/bitwarden.sh#L37-L38

Tag is: 1.45.1, but:
`COREVERSION="1.44.1"`

2021-12-14 18:40 UTC, cscharf requested changes

2021-12-14 18:40 UTC, cscharf commented on scripts/bitwarden.ps1
> +$coreVersion = "1.45.0"
@joseph-flinn , we are going to want to up this to `1.45.1`. I missed that.

2021-12-14 18:40 UTC, cscharf commented on scripts/bitwarden.sh
> +COREVERSION="1.45.0"
same.

2021-12-15 15:38 UTC, cscharf approved these changes

2021-12-15 15:50 UTC, merged