Support docker compose v2
bitwarden/server pull request #1799
Opened 2022-01-08 19:19 UTC by Julien-Eyraud

## Type of change
- [ ] Bug fix
- [x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Support for both docker compose versions:
- the legacy: docker-compose
- the v2 as a docker plugin: docker compose

## Code changes
A small change in the installations script to choose between the two commands depending on the system setup.

* **install.sh:** Check if legacy or v2 is installed and declare the command to use as a variable.
* **run.sh:** Use the docker compose command variable defined in install.sh

## Testing requirements
Tests all commands:
- install
- start/restart
- stop
- update
- rebuild

## Before you submit
- [x ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [x ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-08 19:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/server?pullRequest=1799) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/server?pullRequest=1799) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/server?pullRequest=1799) it.</sub>

2022-01-13 16:01 UTC, Hinton commented
@joseph-flinn Any thoughts? I suspect we'll want to do the same change for powershell.

Also not sure what we'll do if there are inconsistencies between the two versions of docker compose.

https://github.com/docker/compose-switch could also be an alternative.

2022-01-16 12:48 UTC, Julien-Eyraud commented
I'm not familiar with powershell that's why I didn't provide the support in this PR. For now I'm not aware of any inconsistencies between the two versions. It suppose to be a dropping replacement for the v1. More on the compatibility here https://docs.docker.com/compose/cli-command-compatibility/.

Using compose-switch require another component to be installed that could be avoid IMHO.

2022-02-07 23:47 UTC, joseph-flinn requested changes
@Julien-Eyraud Thanks for your contribution! I apologize for the delay in taking a look at your PR. I've left some comments after testing the changes

2022-02-07 23:47 UTC, joseph-flinn commented on scripts/bitwarden.sh
> +$dccmd --version
`--version` is not supported by `docker compose`

```suggestion
if [[ "$dccmd" == "docker compose" ]]; then
    $dccmd version
else
    $dccmd --version
fi
```

2022-02-07 23:47 UTC, joseph-flinn commented on scripts/bitwarden.sh
> +fi
To follow our current bash coding standards:

```suggestion
then
    dccmd='docker-compose'
else
    dccmd='docker compose'
fi
```

2022-02-07 23:47 UTC, joseph-flinn commented on scripts/run.sh
> +fi
To follow our bash coding standards:
```suggestion
then
    dccmd='docker-compose'
else
    dccmd='docker compose'
fi
```

2022-02-08 13:15 UTC, Julien-Eyraud commented
@joseph-flinn thanks for the review I took your changes into account.

2022-02-08 16:17 UTC, joseph-flinn approved these changes

2022-02-08 16:19 UTC, joseph-flinn commented
@Julien-Eyraud Great! We will get this in with the release this week (targeting Thursday).

2022-02-24 15:36 UTC, joseph-flinn approved these changes

2022-02-24 15:36 UTC, merged