Feature/feature branch docker images
bitwarden/server pull request #1824
Opened 2022-01-21 19:26 UTC by joseph-flinn

## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other

## Objectives
Enable docker image builds on every feature branch. Create an automated way to clean up the docker images when the PR is closed.

## Code changes
* **.github/workflows/build.yml:** Remove the branch constraints on when to push to ACR. Refactor a bit for the ACR and DockerHub portions to match.
* **.github/workflows/cleanup-after-pr.yml:** Add a workflow to clean up feature branch docker images when a branch is merged

## Testing notes
- The `build` pipeline passes and pushes containers to ACR
- Under manual testing of `cleanup-after-pr`, the image tags are removed from ACR.

## Before you submit
- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-21 21:01 UTC, vgrassia requested changes

2022-01-21 22:38 UTC, joseph-flinn commented on .github/workflows/build.yml
> +            docker_repos: [bitwarden, bitwardenqa.azurecr.io]
I don't think so. DockerHub currently only contains images that are used in the self-host install. EventProcessor is strictly a cloud implementation piece.

2022-01-22 16:43 UTC, mimartin12 commented on .github/workflows/build.yml
> +        if: |
```suggestion
        if: |
```
To make linter happy

2022-01-24 16:07 UTC, mimartin12 approved these changes

2022-01-24 16:51 UTC, joseph-flinn commented on .github/workflows/build.yml
> +            docker_repos: [bitwarden, bitwardenqa.azurecr.io]
I misread this. Good catch. I've removed the DockerHub repo and am now only pushing to ACR

2022-01-24 16:52 UTC, mimartin12 approved these changes

2022-01-24 16:57 UTC, vgrassia approved these changes

2022-01-24 19:12 UTC, merged