Feature/self hosted f4 e sync
bitwarden/server pull request #1889
Opened 2022-02-28 15:31 UTC by jlf0dev

## Type of change
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Adds a random, daily job to the API project for a self hosted sponsorship sync. 

Some of these changes were left over from a strategy of adding one trigger per organization. I don't see the harm in leaving them in, as they allow us to add more complicated jobs in the future.

## Code changes

* **src/Core/Settings/GlobalSettings.cs:** add `EnableCloudCommunication` setting
* **src/Api/Jobs/SelfHostedSponsorshipSyncJob.cs:** add job for syncing sponsorships
* **src/Core/Jobs/BaseJobsHostedService.cs:** set Jobs array to take `IJobDetail` instead of just a type. We can then create different jobs in the future inside each projects implementation.
* **src/Api/Jobs/JobsHostedService.cs:** create random daily trigger and self hosted sync job, adding them to the scheduler
* **src/Api/Startup.cs:** pass in global settings to job scheduler and remove extra code

## Testing requirements

## Before you submit
- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-02-28 21:53 UTC, MGibson1 requested changes
The scaffolding for the new job looks good, We need to get Justin's API work in so we can pull Orgs with billing sync keys to iterate through.

2022-02-28 21:53 UTC, MGibson1 commented on src/Core/Settings/GlobalSettings.cs
> +        public virtual bool EnableCloudCommunication { get; set; }
We want to make sure this defaults to false.

2022-03-02 14:36 UTC, jlf0dev commented on src/Api/Jobs/JobsHostedService.cs
> +            var jobs = new List<Tuple<IJobDetail, ITrigger>>
The `JobDetail.Key` looks like `DEFAULT.Bit.Api.Jobs.AliveJob`, meaning we won't lose out on any logging quality.

If the dangers outweigh the benefits of this change I can revert, but with our original implementation we could only schedule one type of job.

2022-03-24 14:22 UTC, closed without merging

2022-03-24 14:23 UTC, jlf0dev commented
moved to #1922