[PS-7] change revert email copy and add ValidUntil to sponsorship
bitwarden/server pull request #1965
Opened 2022-04-21 20:39 UTC by jlf0dev

## Type of change
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Changed the copy for RevertSponsorship emails

Added the `ValidUntil` property to sponsorships whenever they are modified

## Code changes

* **file.ext:** Description of what was changed and why

## Testing requirements

- Check for correct email copy when invoice upcoming event is sent from stripe

## Before you submit
- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-04-21 21:10 UTC, justindbaur approved these changes
Looks great!

2022-04-21 22:51 UTC, MGibson1 requested changes
One concern

2022-04-21 22:51 UTC, MGibson1 commented on src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateSponsorshipCommand.cs
> +                            sponsorship.ValidUntil.GetValueOrDefault());
Not so sure about this. What about defaulting to UtcNow + 15 days?

2022-04-22 13:21 UTC, MGibson1 approved these changes

2022-04-22 13:33 UTC, merged