[PS-589] Fix DeviceUnknownVerification User_Update proc
bitwarden/server pull request #2041
Opened 2022-06-08 14:42 UTC by fedemkr

## Type of change (mark with an `X`)

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix `2022-05-24_00_DeviceUnknownVerification ` User_Update stored procedure to remove the NULL on the `UnknownDeviceVerificationEnabled` parameter and set the default value on it

## Code changes

* **2022-05-24_00_DeviceUnknownVerification.sql:** Removed NULL and set default value on `UnknownDeviceVerificationEnabled` on the `User_Update` stored procedure
## Before you submit (mark with an `X`)

```
- [X] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-08 15:01 UTC, joseph-flinn submitted a review, later dismissed

2022-06-08 15:43 UTC, Hinton requested changes
Have we updated the refrence sproc in the sqlproj?

2022-06-09 18:24 UTC, joseph-flinn approved these changes
Looks good to me. Might want confirmation from Oscar as I'm not an expert in this area.

2022-06-13 14:42 UTC, Hinton approved these changes

2022-06-13 14:42 UTC, merged