PS-93 - PS-93-distributed-ip-rate-limiting
bitwarden/server pull request #2060
Opened 2022-06-14 22:18 UTC by shane-melton

## Type of change

- [X] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

## Code changes

### Package Changes for src/Core/Core.csproj:
* Upgrade `AspNetCoreRateLimit` to 4.0.2 and add `AspNetCoreRateLimit.Redis@1.0.1` to gain Redis support. 
* Replace/upgrade `Microsoft.Extensions.Caching.Redis` with `Microsoft.Extensions.Caching.StackExchangeRedis` as the former is no longer supported and has dependency conflicts with `AspNetCoreRateLimit@4.0.2`
* Upgrade `NewtonSoft.Json` to 13.0.1 as it is a required for the latest `AspNetCoreRateLimit` package. I did not find any breaking changes with the upgrade, and I know we are moving away from NewtonSoft.Json internally so I don't believe it will be a problem.

### Other Changes:
* **src/[Api | Identity]/Startup.cs:** Configure necessary services for Ip rate limiting and the distributed Redis cache

* **src/Core/HostedServices/IpRateLimitSeedStartupService.cs:** Added a hosted service to seed any Ip rate limit policies on initial application startup. (Avoids modifying `Program.cs`, which can get messy)
* **src/SharedWeb/Utilities/ServiceCollectionExtensions.cs:** Add two extensions to consistently add distributed caching and ip rate limiting across all projects. Remove the distributed cache service configuration out of `AddDistributedIdentityServices()` as those are now configured by `AddDistributedCache()`
* **src/Core/Settings/GlobalSettings.cs:** Add a _general_ Redis connection string that is used by the new service collection extensions to add distributed caching to the project. Having a single Redis instance shared between all the projects should make the infrastructure requirements and configurations simpler/cleaner going forward. 
* **src/Core/Utilities/CustomIpRateLimitMiddleware.cs:** Updated for breaking changes due to `AspNetCoreRateLimit` package upgrade. Now using an `IDistributedCache` for storing/retrieving IP block counts.
* **src/Core/Utilities/DistributedCacheExtensions.cs:** Some helper extensions when interacting with the `IDistributedCache` service.

## Before you submit

- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [X] This change has particular **deployment requirements** (notify the DevOps team)

2022-06-20 18:58 UTC, justindbaur requested changes

2022-06-20 18:58 UTC, justindbaur commented on src/Core/Utilities/CustomIpRateLimitMiddleware.cs
> +            foreach (var query in httpContext.Request.Query) s += $"Query \"{query.Key}\": {query.Value} \n";
nit: We use curly braces even on single line statements. https://contributing.bitwarden.com/code-style/#control-blocks

2022-06-20 18:58 UTC, justindbaur commented on src/Core/Utilities/CustomIpRateLimitMiddleware.cs
> +                : _options.QuotaExceededMessage;
I like this refactor.

2022-06-20 18:58 UTC, justindbaur commented on src/Core/Utilities/DistributedCacheExtensions.cs
> +        public static bool TryGetValue<T>(this IDistributedCache cache, string key, out T value)
I love the `bool Try... out` pattern ❤️

2022-07-13 21:23 UTC, justindbaur reviewed
Looks good, looks like some tests are failing though. Might need to rebase off master. 

@mimartin12 Are we able to test this in QA?

2022-07-14 21:45 UTC, shane-melton commented
That failing test is fixed now

2022-07-19 18:28 UTC, mimartin12 approved these changes

2022-07-19 18:58 UTC, merged