[EC-530] SCIM CQRS Refactor - Groups/Post
bitwarden/server pull request #2270
Opened 2022-09-09 15:30 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Refactor the SCIM API to use the CQRS pattern which implies that each action must be isolated in a specific command to do only one specific task.
Added unit tests to check that each command completes its task.

## Code changes
* **bitwarden-server.sln:** Added new unit tests project Scim.Test
* **bitwarden_license/src/Scim/Commands/Groups/Interfaces/*:** SCIM group endpoints command interfaces
* **bitwarden_license/src/Scim/Commands/Groups/*:** SCIM group endpoints command implementations
* **bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs:** Updated to use commands and handle exceptions
* **bitwarden_license/src/Scim/Startup.cs:** Registered commands for injection
* **bitwarden_license/test/Scim.Test/Commands/Groups/*:** SCIM group command unit tests
* **bitwarden_license/test/Scim.Test/Scim.Test.csproj:** New unit test project for SCIM
* **bitwarden_license/test/Scim.Test/packages.lock.json:** Scim.Test project package dependencies
* **src/Core/Exceptions/BadRequestException.cs:** Added parameterless constructor
* **src/Core/Exceptions/ConflictException.cs:** Added a new Exception type for Conflict
* **src/Core/Exceptions/NotFoundException.cs:** Added parameterless constructor

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-14 01:34 UTC, eliykat requested changes

2022-10-14 01:34 UTC, eliykat commented on bitwarden_license/src/Scim/Groups/PostGroupCommand.cs
> +        if (!memberIds.Any() && skipIfEmpty)
You can remove the `skipIfEmpty` param here, but otherwise leave this block in (because `skipIfEmpty` is always `true` at the moment)

2022-10-14 01:34 UTC, eliykat commented on bitwarden_license/test/Scim.Test/Groups/PostGroupCommandTests.cs
> +        await sutProvider.GetDependency<IGroupRepository>().Received(1).UpdateUsersAsync(Arg.Any<Guid>(), Arg.Any<IEnumerable<Guid>>());
Please assert user ids

2022-10-17 01:57 UTC, eliykat requested changes
Looks good, but we'll need to remove `UpdateGroupMembersAsync` in the controller. Let's merge the Groups/Put PR first (which also uses that method), then update this branch and remove it here.

Otherwise we're at risk of leaving an orphan method in the controller.

2022-10-17 12:07 UTC, r-tome commented
> Looks good, but we'll need to remove `UpdateGroupMembersAsync` in the controller. Let's merge the Groups/Put PR first (which also uses that method), then update this branch and remove it here.
> 
> Otherwise we're at risk of leaving an orphan method in the controller.

I created a new feature branch (`feature/scim-cqrs`) to merge all PRs into and I've already merged Groups/Put and removed `UpdateGroupMembersAsync`.

2022-10-18 01:21 UTC, eliykat approved these changes

2022-10-18 09:29 UTC, merged