Defect/SG-977 - Org domain event logs missing details
bitwarden/server pull request #2573
Opened 2023-01-12 21:22 UTC by JaredSnider-Bitwarden

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

For domain verification event logs generated from the background job, create custom system user type of DomainVerification so it can be displayed in the member column of the event logs screen on the client.  Create a new device type of server so the client doesn't have to show unknown, and apply this to existing SCIM logs. 
- Fix missing EventSystemUser.SCIM property on user restore / revoke 

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-12 22:59 UTC, JaredSnider-Bitwarden commented
@r-tome , I'm new to this style of backend unit tests. I'm not sure where the parameters are coming from for the failing test `LogOrganizationUserEvent_WithEventSystemUser_LogsRequiredInfo`?   I think changing the deviceType in the `EventService.CreateLogOrganizationUserEventsAsync` method maybe is what has broken the test?

2023-01-13 11:48 UTC, r-tome requested changes
@JaredSnider-Bitwarden the values for the parameters in the unit tests come from the `BitAutoData` attribute, they are random values so we don't have to define them every time.

You can fix the test by removing the `DeviceType` parameter because in that test scenario since we're writing an Event with a `EventSystemUser` value then we know that the `DeviceType` will be Server. Then change the expected value to this:

```
var expected = new List<IEvent>() {
            new EventMessage()
            {
                IpAddress = ipAddress,
                DeviceType = DeviceType.Server,
                OrganizationId = orgUser.OrganizationId,
                UserId = orgUser.UserId,
                OrganizationUserId = orgUser.Id,
                ProviderId = providerId,
                Type = eventType,
                ActingUserId = actingUserId,
                Date = date,
                SystemUser = eventSystemUser,
            }
        };
```

2023-01-13 11:48 UTC, r-tome commented on src/Core/Services/Implementations/EventService.cs
> +        if (systemUser is EventSystemUser.SCIM)
All Events with a defined `SystemUser` should have the new `DeviceType.Server` value so I'd move that logic up to the `EventMessage` constructor:

```
var e = new EventMessage(_currentContext)
        {
            OrganizationId = group.OrganizationId,
            GroupId = group.Id,
            Type = type,
            ActingUserId = _currentContext?.UserId,
            ProviderId = await GetProviderIdAsync(@group.OrganizationId),
            Date = date.GetValueOrDefault(DateTime.UtcNow),
            SystemUser = systemUser,
            DeviceType = systemUser.HasValue ? DeviceType.Server : null
        };
```

2023-01-13 11:48 UTC, r-tome commented on src/Core/Services/Implementations/EventService.cs
> +            if (systemUser is EventSystemUser.SCIM)
Same thing as on the `CreateLogGroupEventAsync` method - set `DeviceType = systemUser.HasValue ? DeviceType.Server : null` in the `EventMessage` class instantiation.

2023-01-13 15:27 UTC, JaredSnider-Bitwarden commented
> @JaredSnider-Bitwarden the values for the parameters in the unit tests come from the `BitAutoData` attribute, they are random values so we don't have to define them every time.
> 
> You can fix the test by removing the `DeviceType` parameter because in that test scenario since we're writing an Event with a `EventSystemUser` value then we know that the `DeviceType` will be Server. Then change the expected value to this:
> 
> ```
> var expected = new List<IEvent>() {
>             new EventMessage()
>             {
>                 IpAddress = ipAddress,
>                 DeviceType = DeviceType.Server,
>                 OrganizationId = orgUser.OrganizationId,
>                 UserId = orgUser.UserId,
>                 OrganizationUserId = orgUser.Id,
>                 ProviderId = providerId,
>                 Type = eventType,
>                 ActingUserId = actingUserId,
>                 Date = date,
>                 SystemUser = eventSystemUser,
>             }
>         };
> ```

Ah, I almost got that right with trying to set the expected deviceType, but I couldn't figure out the AutoData piece. Thank you very much for the explanation.

2023-01-13 16:11 UTC, r-tome commented on src/Core/Services/Implementations/EventService.cs
> +        if (systemUser is EventSystemUser.SCIM)
That makes perfect sense, I'm happy with it being this way.

2023-01-13 16:12 UTC, r-tome approved these changes
Looks great to me, good job!

2023-01-13 16:13 UTC, merged