[SM-568] Delete service accounts
bitwarden/server pull request #2748
Opened 2023-02-27 16:25 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement delete service accounts.

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-27 18:01 UTC, Thomas-Avery requested changes
A couple of minor changes and one question.

2023-02-27 19:31 UTC, Hinton commented on bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/ServiceAccountRepository.cs
> +
Good catch.

2023-02-28 18:20 UTC, Thomas-Avery submitted a review, later dismissed
LGTM

2023-03-02 13:40 UTC, Hinton commented
I accidentally deleted my gpg public key while reinstalling my machine. Rebased with a signed commit.

2023-03-03 22:56 UTC, Thomas-Avery approved these changes

2023-03-06 19:25 UTC, merged