Pm 1191 collections cannot be managed in family organization
bitwarden/server pull request #2765
Opened 2023-03-03 13:31 UTC by coroiu

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Fix issue reported by users that org vault is broken after OAVR v2 when using EF.

## Code changes
EF6 is currently not able to translate LINQ that include selects after `group` statements (see [github issue](https://github.com/dotnet/efcore/issues/26748)). Using `join` let's us bypass this issue.

This new solution is probably a bit faster too so win-win :)

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-03-03 13:38 UTC, jlf0dev approved these changes

2023-03-03 14:05 UTC, justindbaur commented
Maybe I am missing something but isn't this now saying every collection has access groups and users associated to it if ANY do?

I have a group that only has the Default Collection:
![image](https://user-images.githubusercontent.com/19896123/222740066-05faf43a-d4f0-4681-a8f3-e12f9af1a752.png)

But two collection show that they have that group assigned.

![image](https://user-images.githubusercontent.com/19896123/222739968-b58864a4-cd75-4504-8a0b-cfdfd69bf872.png)

2023-03-03 14:12 UTC, justindbaur requested changes
See above concern

2023-03-03 14:28 UTC, coroiu commented
Nice catch!

2023-03-03 14:30 UTC, coroiu commented
Nice catch, should be fixed now!

2023-03-03 14:37 UTC, justindbaur approved these changes
Looks great, thanks.

2023-03-06 23:24 UTC, cvondra commented
If these changes were approved why are they not being pulled into the dev build?

2023-03-07 10:31 UTC, coroiu commented
@cvondra waiting for QA, if vault team has different processes then feel free to merge :)

2023-03-07 13:34 UTC, justindbaur commented
@coroiu Part of the reason that unified is in beta is because QA doesn't have infrastructure or capacity to test each feature branch right now for EF databases. Since this is an EF change only and I ran it locally we can just merge this. 

@cvondra I'm going to merge this now and it will be in the `dev` tag shortly.

2023-03-07 13:35 UTC, merged

2023-03-07 13:56 UTC, cvondra commented
Latest push to /dev works perfectly.