[PM 202] Activate Organization when Stripe Subscription is Activated
bitwarden/server pull request #2820
Opened 2023-03-22 16:46 UTC by cyprain-okeke

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Activate Organization when Stripe Subscription is Activated via the webhook

## Code changes

* **src/Billing/Controllers/StripeController.cs:** Check for Active subscription status and enable the organization if the subscription is active.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-03-27 10:05 UTC, r-tome commented on src/Billing/Controllers/StripeController.cs
This looks great but perhaps the code readability can be improved.
What do you think about creating variables:
```
var organizationId = ids.Item1.Value;
var userId = ids.Item2.Value;
```

2023-03-27 22:03 UTC, eliykat commented on src/Billing/Controllers/StripeController.cs
[Named tuples](https://josef.codes/c-sharp-tips-and-tricks-02-named-tuples/) are great for this!

2023-03-28 13:17 UTC, r-tome requested changes
Declare the `organizationId` and `userId` variables up top and use them everywhere to replace `ids.Item1.Value` and `ids.Item2.Value`.

2023-03-28 14:24 UTC, cyprain-okeke commented
> Declare the `organizationId` and `userId` variables up top and use them everywhere to replace `ids.Item1.Value` and `ids.Item2.Value`.

2023-03-29 09:11 UTC, r-tome approved these changes
Good job 👍

2023-04-11 16:09 UTC, merged