[PM-1188] Server owner auth migration
bitwarden/server pull request #2825
Opened 2023-03-27 17:30 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Completes the auth file moves for server. 

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-03-28 19:48 UTC, jlf0dev commented on src/Admin/Startup.cs
> +             o.ViewLocationFormats.Add("/Auth/Views/{1}/{0}.cshtml");
Point of interest: MVC uses file based routing, so this piece of code tells it where to look for the missing views.

2023-04-12 22:20 UTC, MGibson1 requested changes
The only concerns I have are those two cshtml files.

2023-04-12 22:20 UTC, MGibson1 commented on src/Admin/Auth/Views/_ViewImports.cshtml
This file is registering as net-new. I think you forgot to delete the one located at `src/Admin/Views/_ViewImports.cshtml`

2023-04-12 22:20 UTC, MGibson1 commented on src/Admin/Auth/Views/_ViewStart.cshtml
This file is registering as net-new. I think you forgot to delete the one located at `src/Admin/Views/_ViewStart.cshtml`

2023-04-12 22:20 UTC, MGibson1 commented on src/Api/Auth/Models/Request/Accounts/PasswordRequestModel.cs
Might be wrong here, but I think the usage of this model was overloaded in Clients for something like Send password changes. Can you double check?

2023-04-12 22:20 UTC, MGibson1 commented on src/Core/Services/Implementations/HandlebarsMailService.cs
> +        await AddMessageContentAsync(message, "Auth.VerifyEmail", model);
Nice.

When we start moving to mailers, this will be less of a problem because the mailer will live next to the templates again

2023-04-13 13:21 UTC, jlf0dev commented on src/Admin/Auth/Views/_ViewStart.cshtml
There needs to be a copy of `_ViewStart.cshtml` for each folder container views if they're not subfolders of each other.

2023-04-13 13:21 UTC, jlf0dev commented on src/Admin/Auth/Views/_ViewImports.cshtml
There needs to be a copy of `_ViewImports.cshtml` for each folder container views if they're not subfolders of each other.

2023-04-13 13:41 UTC, MGibson1 commented on src/Api/Auth/Models/Request/Accounts/PasswordRequestModel.cs
If this model is used for more than just updating the password of a user account, that would cause a conflict in the ownership of the model, specifically with the tools team.

I'm just asking to make sure I'm misremembering the reuse of this model, but when I moved models in the client, I remember some inappropriate reuse of models across different functions. I think I remember password request to be one of them

2023-04-13 14:13 UTC, jlf0dev commented on src/Api/Auth/Models/Request/Accounts/PasswordRequestModel.cs
Gotcha. Doesn't seem to be any usages besides auth concerns. It's extended for kdf purposes but that's not in auth folders

2023-04-13 14:16 UTC, jlf0dev commented on src/Admin/Auth/Views/_ViewStart.cshtml
Seems like it. It wouldn't recognize the layout until I added the `_ViewStart.cshtml` to reference it

2023-04-13 20:09 UTC, MGibson1 submitted a review, later dismissed

2023-04-14 16:36 UTC, MGibson1 approved these changes

2023-04-14 17:25 UTC, merged