Pm 1880 extract organization service invite user s async save user async and update user groups async to commands
bitwarden/server pull request #2898
Opened 2023-05-02 16:04 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-06-05 05:31 UTC, eliykat requested changes
This looks great, thanks!

Is there any new or rewritten code in here, or is all just a lift & shift to the new commands, plus updating dependencies?

Please also resolve conflicts, thanks for your patience while I got to this review!

2023-06-09 15:15 UTC, r-tome commented on src/Core/OrganizationFeatures/OrganizationUsers/SaveOrganizationUserCommand.cs
> +        }
Yes, this was a merge issue. Its now fixed. Thanks for noticing

2023-06-09 15:21 UTC, r-tome commented on src/Core/OrganizationFeatures/OrganizationUsers/SaveOrganizationUserCommand.cs
> +    public SaveOrganizationUserCommand(
Makes sense!

2023-06-09 15:23 UTC, r-tome commented on src/Core/OrganizationFeatures/OrganizationUsers/InviteOrganizationUserCommand.cs
> +    internal (bool canScale, string failureReason) CanScale(Organization organization,
I agree, `OrganizationService` has so much stuff in it that you can't see clearly what goes together.

2023-06-09 15:47 UTC, r-tome commented on src/Core/OrganizationFeatures/OrganizationUsers/OrganizationUserCommand.cs
> +public abstract class OrganizationUserCommand
> This looks great, thanks!
> 
> Is there any new or rewritten code in here, or is all just a lift & shift to the new commands, plus updating dependencies?
> 
> Please also resolve conflicts, thanks for your patience while I got to this review!

Yes, its just lift and shift.
So many conflicts, it took me a while to fix all of it.

Thanks for reviewing it!

2023-08-08 22:07 UTC, eliykat commented
@r-tome I think you've split this out into separate PRs now, should we close this one?

2023-08-09 08:08 UTC, closed without merging