[DEVOPS-1517] -  Update Server release to pull from Prod ACR
bitwarden/server pull request #3169
Opened 2023-08-09 12:11 UTC by Eeebru

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

- Makes server release to pull from Prod ACR.
- Push only Server image to Docker.

## Code changes

* .github/workflows/release.yml

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-08-09 13:37 UTC, Eeebru commented on .github/workflows/release.yml
> +        if: matrix.origin_docker_repo == 'bitwarden'
Actually not needed, I only need this for the server Image, so I can as well use the `project_name`, thanks.

2023-08-09 13:51 UTC, michalchecinski approved these changes

2023-08-09 14:25 UTC, mimartin12 commented on .github/workflows/release.yml
> +
🎨  `AZ_REGISTRY` was used in previous instances of setting `env:` values. Please consider updating this one to match https://github.com/bitwarden/server/pull/3157/files/efcacac3709d109ab55d2380b0ed000430c8c571#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R14 or vice versa.

2023-08-09 15:06 UTC, vgrassia requested changes

2023-08-09 15:06 UTC, vgrassia commented on .github/workflows/release.yml
> +          docker push bitwarden/$PROJECT_NAME:latest
Where are we tagging this to push? Why are we pushing `Server` here instead of in the `self-host` repository with the rest of the images?

2023-08-10 16:20 UTC, vgrassia submitted a review, later dismissed

2023-08-14 14:55 UTC, vgrassia approved these changes

2023-08-14 14:56 UTC, merged