Manually move future migrations
bitwarden/server pull request #3263
Opened 2023-09-11 14:57 UTC by joseph-flinn

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Manually orchestrating our EDD processes: moving the future scripts (soon to be officially known as Finalization migrations).

## Code changes

* **util/Migrator/DbScripts/2023-09-11_00_FutureMigration.sql:** Move future migration to be run this release
* **util/Migrator/DbScripts/2023-09-11_01_FutureMigration.sql:** Move future migration to be run this release

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-09-12 14:07 UTC, Hinton requested changes
I believe we should also move `dbo_future` and overwrite existing files.

And the migrations most likely won't work since `User_Create` has new columns that don't seem to be reflected.

2023-09-12 14:31 UTC, Hinton commented
@joseph-flinn run git blame and ping the authors to update the scripts.

2023-09-12 19:30 UTC, joseph-flinn commented
@Hinton The `src/Sql/dbo_future` scripts have all been moved to their corresponding `src/Sql/dbo` directories

2023-09-14 18:31 UTC, Hinton commented on src/Sql/dbo/Tables/User.sql
@fedemkr this file seems to need updating.

2023-09-14 19:03 UTC, Hinton submitted a review, later dismissed
Looks like everything is updated as expected

2023-09-14 19:19 UTC, joseph-flinn commented
After discussing with QA, we are going to hold this PR for the October release.

2023-10-16 19:39 UTC, joseph-flinn commented
@Hinton I need to request another review since https://github.com/bitwarden/server/pull/3192 changed the directory name

2023-10-19 14:52 UTC, Hinton approved these changes

2023-10-19 14:59 UTC, merged