[PM-212] Sync Organization Billing Email from Stripe Webhook
bitwarden/server pull request #3305
Opened 2023-09-28 16:30 UTC by amorask-bitwarden

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

[PM-212](https://bitwarden.atlassian.net/browse/PM-212)

This PR has two purposes:
1. Refactor out various private methods within the `StripeController` into a `StripeEventService` for better maintainability and testability.
2. Begin handling the Stripe `customer.updated` event in the `StripeController` to update an organization's billing email when an organization customer is updated in Stripe.

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-10-04 11:27 UTC, djsmith85 commented
I assume this PR and https://github.com/bitwarden/server/pull/3319 will largely require reviews from @bitwarden/team-billing-dev and not just from @bitwarden/team-tools-dev.

@cturnbull-bitwarden Could you please look into adding CODEOWNERS for the billing-owned components.

2023-10-04 13:10 UTC, cturnbull-bitwarden approved these changes
👍 Nice work!

2023-10-04 18:07 UTC, djsmith85 requested changes

2023-10-04 18:07 UTC, djsmith85 commented on src/Core/Tools/Enums/ReferenceEventType.cs
> +    OrganizationEditedInStripe,
I don't see this used anywhere? Is this part of some other work?

2023-10-05 21:03 UTC, djsmith85 commented on src/Core/Tools/Enums/ReferenceEventType.cs
> +    OrganizationEditedInStripe,
Dicussed this with @amorask-bitwarden and I just missed the usage in the StripeController. Changes are looking good.

2023-10-05 21:04 UTC, djsmith85 approved these changes
Approving changes for @bitwarden/team-tools-dev

2023-10-11 19:57 UTC, merged