[AC-1717] Update default values for LimitCollectionCreationDeletion
bitwarden/server pull request #3365
Opened 2023-10-20 04:48 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

In the initial implementation, `LimitCollectionCreationDeletion` defaulted to 1 in the table schema but 0 in the create sproc. This makes sense when merge == release, but now that we're merging early behind feature flags, we need to adjust this.

## Code changes

* sql code
  * make `LimitCollectionCreationDeletion` default to 1 in the organization create sproc. This covers any rollback scenario where the server is not providing a value
  * cleanup task: delete the old column name. I didn't bother doing this initially, but thinking about it more, it's probably floating around on QA instances. It won't do anything in production because that column never existed.
* `OrganizationService` - set `LimitCollectionCreationDeletion` when an organization is created, based on the feature flag:
  * flag = OFF (pre-release) -> setting is ON (members cannot create/delete collections, same as today)
  * flag = ON (post-release) -> setting is OFF (members can create/delete collections)

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-10-20 12:11 UTC, MGibson1 requested changes

2023-10-20 17:27 UTC, vincentsalucci commented on src/Core/Services/Implementations/OrganizationService.cs
> +        var flexibleCollectionsIsEnabled =
I concur with this. I don't believe `flexibleCollectionsIsEnabled` should have a `!`

2023-10-22 22:30 UTC, eliykat commented on src/Core/Services/Implementations/OrganizationService.cs
> +        var flexibleCollectionsIsEnabled =
Yikes, yes that is a stray `!`!

2023-10-24 00:02 UTC, vincentsalucci approved these changes

2023-10-24 00:46 UTC, merged