[AC-1779] Fix validation for ExpirationWithoutGracePeriod in OrganizationLicense
bitwarden/server pull request #3403
Opened 2023-11-02 09:53 UTC by cyprain-okeke

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

OrganizationLicense.VerifyData is missing validation for the ExpirationWithoutGracePeriod property that was added by Billing Team. Please fix this following the pattern in the rest of that method and request a review from AC Team.

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-11-02 12:33 UTC, withinfocus commented
This needs to be some kind of datetime-oriented check, right? To ensure one date is less than the other.

2023-11-02 14:55 UTC, MGibson1 requested changes
⚠️ This is in direct conflict to creation of an org license done [here](https://github.com/bitwarden/server/blob/master/src/Core/Entities/Organization.cs#L254).

Unless expiration date is equal to expiration date without grace period, these aren't going to be equal

2023-11-03 01:50 UTC, eliykat commented
I agree with @MGibson1 - I didn't look too closely at this before creating a ticket, it just looked like a miss because it's different to the established pattern.

I'm not sure about adding a db column for it - it's been a while since I looked at this, but why can't we just calculate the grace period date from the expiration date, or vice versa? It would be good to follow up and see if there's a better way of doing this.

For now my only real request is to add a comment here noting that v12 is intentionally excluded, e.g.

```cs
// Version 12 added ExpirationWithoutDatePeriod, but that property is informational only and is not saved
// to the Organization object. It's validated as part of the hash but does not need to be validated here.
```

2023-11-23 21:20 UTC, eliykat approved these changes

2023-12-27 14:48 UTC, cturnbull-bitwarden approved these changes

2023-12-27 15:02 UTC, r-tome approved these changes

2024-06-11 14:14 UTC, MGibson1 approved these changes

2024-06-11 14:26 UTC, merged