[AC-1828] [AC-1807] Aggregated admin panel pricing fixes
bitwarden/server pull request #3448
Opened 2023-11-14 17:08 UTC by amorask-bitwarden

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

- [AC-1828](https://bitwarden.atlassian.net/browse/AC-1828)
- [AC-1807](https://bitwarden.atlassian.net/browse/AC-1807)

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

[AC-1828]: https://bitwarden.atlassian.net/browse/AC-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AC-1807]: https://bitwarden.atlassian.net/browse/AC-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-14 17:10 UTC, cturnbull-bitwarden submitted a review, later dismissed

2023-11-14 22:42 UTC, eliykat requested changes

2023-11-14 22:42 UTC, eliykat commented on util/Migrator/DbScripts/2023-11-14_00_UpdateOrganizationUnassignedToProviderSearch.sql
The files in `src/Sql` represent the current state of the SQL database (tables, sprocs, etc). Migration scripts like this one provide the migration path to reach that current state. So both `src/Sql` and `util/Migrator` need to be kept in sync.

In this case, you've written a new migration, but you need to update the [sproc itself](https://github.com/bitwarden/server/blob/master/src/Sql/dbo/Stored Procedures/Organization_UnassignedToProviderSearch.sql) to match.

(This is what the failing job is doing - it compares the SQL files against the migration scripts to make sure they match.)

It might also be nice to add a comment to explain what/why the change is here.

2023-11-15 14:38 UTC, amorask-bitwarden commented on util/Migrator/DbScripts/2023-11-14_00_UpdateOrganizationUnassignedToProviderSearch.sql
@eliykat Thanks a ton for this explanation; didn't realize that but makes perfect sense. I've added another commit based on your feedback here: https://github.com/bitwarden/server/pull/3448/commits/4bcfad87b7a8456a28f9b217849bfae4293e8fd9

2023-11-16 03:47 UTC, rkac-bw commented on util/Migrator/DbScripts/2023-11-14_00_UpdateOrganizationUnassignedToProviderSearch.sql
SQL looks good to me

2023-11-16 04:17 UTC, withinfocus commented on util/Migrator/DbScripts/2023-11-14_00_UpdateOrganizationUnassignedToProviderSearch.sql
> +GO
⛏️ (and like the old days) end files in newlines.

2023-11-16 14:43 UTC, cturnbull-bitwarden approved these changes
👍 TY

2023-11-17 14:07 UTC, eliykat reviewed
My feedback has been resolved

2023-11-17 19:51 UTC, rkac-bw approved these changes
Looks good to me

2023-11-17 20:09 UTC, eliykat approved these changes

2023-11-17 20:12 UTC, merged