SM-1012: Removing SM Beta (Phase 2)
bitwarden/server pull request #3663
Opened 2024-01-12 17:25 UTC by coltonhurst

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Now that phase 1 of SM beta is complete, in phase 2 we remove all references to SecretsManagerBeta in the server project, but leave the references in the db for phase 3. We need to do this to ensure compatibility between the current and previous version of server with the database.

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2024-01-16 20:07 UTC, cturnbull-bitwarden approved these changes

2024-01-16 22:19 UTC, Thomas-Avery requested changes
Looks good, just need to add EF migrations.

2024-01-18 17:16 UTC, coltonhurst commented on src/Core/AdminConsole/Entities/Organization.cs
> -    public bool SecretsManagerBeta { get; set; }
Good call, thank you! Fixed in [d6a8a0f](https://github.com/bitwarden/server/pull/3663/commits/d6a8a0facbd715ea4eff3a19af6079b44389fcd1)

2024-01-18 17:54 UTC, Thomas-Avery submitted a review, later dismissed
Looks good.

2024-01-18 20:36 UTC, rkac-bw approved these changes
looks good to me

2024-01-18 23:47 UTC, vincentsalucci approved these changes
Reviewed the AC team owned files. Quick question: how **good** did making this PR feel? 😄

2024-01-19 13:12 UTC, cturnbull-bitwarden approved these changes

2024-01-31 22:05 UTC, coltonhurst commented
@vincentsalucci @cturnbull-bitwarden @rkac-bw @Thomas-Avery I'll need a review one more time if you don't mind!

This has been approved by QA, but I re-ran the EF migrations so that the date would be updated. This should be the only change since the last review.

Thank you!

2024-01-31 22:33 UTC, vincentsalucci approved these changes
Approved AC file changes 👍

2024-01-31 23:00 UTC, cturnbull-bitwarden approved these changes

2024-02-01 00:04 UTC, Thomas-Avery approved these changes

2024-02-05 17:37 UTC, rkac-bw approved these changes
Looks good to me

2024-02-05 20:51 UTC, merged