[AC-2646] Remove FC MVP dead code from Core
bitwarden/server pull request #4281
Opened 2024-06-25 20:00 UTC by vincentsalucci

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2646

## 📔 Objective

> Remove FC MVP dead code from the following: `CreateGroupCommand`, `UpdateGroupCommand`, `UpdateOrganizationUserCommand`, `OrganizationService`, `CollectionService`, `CipherService`

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-05 01:10 UTC, eliykat requested changes
A few code review comments, I have also fixed various tests here: https://github.com/bitwarden/server/pull/4467

2024-07-05 17:36 UTC, vincentsalucci commented on test/Core.Test/Vault/Services/CipherServiceTests.cs
>      public async Task ImportCiphersAsync_IntoOrganization_WithFlexibleCollectionsEnabled_Success(
`WithFlexibleCollectionsEnabled`
`WithFlexibleCollections`
`FlexibleCollectionsDisabled`
`WithoutFlexibleCollections`

2024-07-09 13:31 UTC, r-tome approved these changes

2024-07-11 01:43 UTC, eliykat submitted a review, later dismissed
Nice work 🎉

2024-07-11 22:19 UTC, shane-melton approved these changes
Vault changes look good!

2024-07-12 03:04 UTC, vincentsalucci commented
@eliykat @shane-melton @r-tome Sorry ya'll - had to fix some conflicts!

2024-07-12 05:10 UTC, eliykat approved these changes

2024-07-12 15:16 UTC, shane-melton approved these changes

2024-07-12 17:25 UTC, merged