Refactored `Index` to use `UserModel` instead of entity. Added test for mapping and removed placeholder.
bitwarden/server pull request #4797
Opened 2024-09-23 20:50 UTC by jrmccannon

## 🎟️ Tracking
https://bitwarden.atlassian.net/browse/PM-12074

## 📔 Objective
Instead of using the entity model for the User which is directly tied to the database, I switched out the model for a lightweight view model that can be used to hold only what that page needs.  This will allow it to be expanded for properties that aren't directly on the database model.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-25 09:47 UTC, r-tome requested changes

2024-09-25 09:47 UTC, r-tome commented on src/Admin/Controllers/UsersController.cs
> -        if (_featureService.IsEnabled(FeatureFlagKeys.MembersTwoFAQueryOptimization))
The feature flag lookup, should be kept here. We only want to execute that query if its enabled

2024-09-25 09:47 UTC, r-tome commented on src/Admin/Models/UserModel.cs
Instead of creating a new model can we refactor `UserViewModel`?

2024-09-25 09:47 UTC, r-tome commented on test/Admin.Test/Models/UserModelTests.cs
Use `[SutProviderCustomize]` to automatically create the fixture and `[BitAutoData]` to create test data

2024-09-27 16:46 UTC, jrmccannon commented on src/Admin/Models/UserModel.cs
Yep! Also had to tweak edit model and all the `.cshtml` files to reflect this.

2024-09-30 15:42 UTC, r-tome approved these changes
Looks good to me! Thanks for making the changes I had requested.

Ensure that QA tests the editing of all User fields that should be modifiable

2024-09-30 18:21 UTC, merged