Return Policy object instead of NotFoundException
bitwarden/server pull request #4911
Opened 2024-10-17 20:50 UTC by BTreston

## 🎟️ Tracking

[PM-13730](https://bitwarden.atlassian.net/browse/PM-13730)

## 📔 Objective

This PR removes the thrown `NotFoundException` when policies are not found and returns a default `Policy` object with the same `Type` sent in the request and the `Enabled` value set to `false`

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-18 09:58 UTC, r-tome requested changes
Please add the ticket ID `[PM-13730]` to the start of the PR title.

Also, add unit tests to [PoliciesControllerTests.cs](https://github.com/bitwarden/server/blob/main/test/Api.Test/Controllers/PoliciesControllerTests.cs) to cover all cases for the `Get` method. Let me know if you need any help!

2024-10-18 09:58 UTC, r-tome commented on src/Api/AdminConsole/Controllers/PoliciesController.cs
>      public async Task<PolicyResponseModel> Get(string orgId, int type)
Lets take this opportunity to change the `orgId` type to `Guid` so its automatically parsed
```suggestion
    public async Task<PolicyResponseModel> Get(Guid orgId, int type)
```

2024-10-18 21:14 UTC, BTreston commented
@r-tome Still a bit shaky on exactly how nunit works, but I think I have the general gist for what these tests should do. Definitely open to more feedback, if these seem totally off base let me know.

2024-10-21 10:23 UTC, r-tome requested changes
We have to keep throwing an exception if the user can't manage policies. Also, lets add tests to cover all possible scenarios

2024-10-21 10:23 UTC, r-tome commented on test/Api.Test/Controllers/PoliciesControllerTests.cs
This is a good starting point, you've definitely got the gist of it but we need to cover all possible scenarios:
- `Get_WhenUserCannotManagePolicies_ThrowsNotFoundException`
	- Assert Exception is thrown
	- Assert type is NotFoundException
- `Get_WhenUserCanManagePolicies_WithExistingType_ReturnsExistingPolicy`
	- Assert returned policy type equals the requested type
	- Assert all other properties equal the database policy
- `Get_WhenUserCanManagePolicies_WithNonExistingType_ReturnsDefaultPolicy`
	- Assert returned object equals an expected new default policy object

2024-10-21 15:29 UTC, r-tome approved these changes
Nice work! Thanks for making the changes

2024-10-28 16:33 UTC, merged