Auth/pm 8107/remove duo metadata v2
bitwarden/server pull request #4934
Opened 2024-10-23 18:14 UTC by ike-kottlowski

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-30 21:09 UTC, JaredSnider-Bitwarden requested changes
Really nice start on these changes! A bit more testing would be great!

2024-11-03 19:44 UTC, ike-kottlowski commented on src/Core/Auth/Services/Implementations/DuoUniversalConfigService.cs
Moving this class to a single method in the `TwoFactorController.cs` will reduce testability since the use of DI here allows us to use `NSubstitute` libraries to mock the responses from this class.

Adding this method to the controller will require some more investigation in order to maintain test coverage.

2024-11-14 18:50 UTC, ike-kottlowski commented
I've updated the description with current screen recordings.

@JaredSnider-Bitwarden

2024-11-18 23:45 UTC, JaredSnider-Bitwarden approved these changes
Really nice work. Thanks for all your efforts adding to our test coverage!

2024-11-18 23:45 UTC, JaredSnider-Bitwarden commented on src/Core/Auth/Identity/TokenProviders/DuoUniversalTokenService.cs
> +public interface IDuoUniversalTokenService
Non-blocking Suggestion: we should generally keep interfaces and implementations in separate files for separation of concerns.

2024-11-18 23:45 UTC, JaredSnider-Bitwarden commented on src/Core/Auth/Identity/TokenProviders/DuoUniversalTokenService.cs
Really appreciate all the excellent documentation you added.

2024-11-18 23:45 UTC, JaredSnider-Bitwarden commented on test/Api.Test/Auth/Controllers/TwoFactorControllerTests.cs
🏅

2024-11-18 23:48 UTC, ike-kottlowski commented on test/Api.Test/Auth/Controllers/TwoFactorControllerTests.cs
💅🏻

2024-11-18 23:58 UTC, merged