PM-13236 PasswordHealthReportApplications DB Tables
bitwarden/server pull request #4958
Opened 2024-10-30 20:13 UTC by voommen-livefront

## 🎟️ Tracking

[
](https://bitwarden.atlassian.net/browse/PM-13236)

## 📔 Objective

Creating database table, view and queries for `dbo.PasswordHealthReportApplications`

## 📸 Screenshots

No screen shots at this time - as these are database changes only.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-30 20:36 UTC, rkac-bw commented on src/Sql/dbo/Stored Procedures/PasswordHealthReportApplications_Create.sql
> +    INSERT INTO dbo.PasswordHealthReportApplications ( Id, OrganizationId, Uri, CreationDate, RevisionDate )
SET NOCOUNT ON; should be present

2024-10-31 16:45 UTC, ttalty submitted a review, later dismissed

2024-10-31 16:49 UTC, rkac-bw approved these changes
lgtm

2024-11-01 17:00 UTC, rkac-bw approved these changes
lgtm

2024-11-01 18:48 UTC, voommen-livefront commented
@ttalty @rkac-bw FYI: changed the name of the table from `PasswordHealthReportApplications` to `PasswordHealthReportApplication` (singular) - this required that I change the file names too.

2024-11-04 15:51 UTC, ttalty approved these changes

2024-11-04 16:22 UTC, ttalty requested changes

2024-11-04 16:22 UTC, ttalty commented on src/Core/AdminConsole/Entities/PasswordHealthReportApplication.cs
Can you move this file to: src\Core\Tools\Entities so we are the code owners for reviews?

2024-11-04 16:47 UTC, ttalty approved these changes
Looks good to go 🚀

2024-11-04 18:48 UTC, rkac-bw approved these changes
LGTM

2024-11-04 19:23 UTC, merged