[PM-14826] Add UsePolicies check to GET endpoints
bitwarden/server pull request #5046
Opened 2024-11-19 15:59 UTC by JimmyVo16

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14826

## 📔 Objective

1. Add a UsePolicies check to `GET organizations/{{orgId}}/policies/master-password` and `GET organizations/{{orgId}}/policies/token`
4. Add unit tests to account for these edge cases.
5. Update a unit to account for the happy path.

## 📸 Screenshots

manually tested the  `GET organizations/{{orgId}}/policies/token` 

For a free Org (sad path).

<img width="2435" alt="image" src="https://github.com/user-attachments/assets/e5e73eab-0a45-4f3f-b078-f22eb06daecb">

For an enterprise Org (happy path).

<img width="2302" alt="image" src="https://github.com/user-attachments/assets/c81e17c9-e5de-4747-a346-eaebf9da24c8">

Note: I'm still tracking down the `GET organizations/{{orgId}}/policies/master-password` in the UI. I will circle back here when I find it.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-19 16:12 UTC, r-tome requested changes
Great work! Just the code format to fix and its good to go. I'll also review the new unit tests if you decide to add them in

2024-11-19 16:12 UTC, r-tome commented on src/Api/AdminConsole/Controllers/PoliciesController.cs
> -        if (!await _currentContext.ManagePolicies(orgId))
Reordering the private properties is fine, but please re-add all the curly brackets to keep the code consistent with the rest of the codebase.

2024-11-19 16:12 UTC, r-tome commented on test/Api.Test/Controllers/PoliciesControllerTests.cs
> +            sutProvider.Sut.GetByToken(orgId, email, token, organizationUserId));
Feel free to add more unit tests if you'd like! While it's not expected for work outside the ticket scope, I'm a big advocate for maximizing test coverage. I really appreciate seeing that effort, kudos!

2024-11-25 11:00 UTC, r-tome submitted a review, later dismissed
Great work!

2024-12-11 20:24 UTC, JimmyVo16 commented
I did a sanity check by starting the Admin service. 

<img width="917" alt="image" src="https://github.com/user-attachments/assets/3a2c2748-4839-46d6-ae8b-8df448aac148" />

2024-12-12 15:18 UTC, merged