[PM-12512] Add Endpoint to allow users to request a new device otp
bitwarden/server pull request #5146
Opened 2024-12-12 06:26 UTC by ike-kottlowski

## 🎟️ Tracking

[PM-12512](https://bitwarden.atlassian.net/browse/PM-12512)

## 📔 Objective

When a user tries to log into a new device they are sent and OTP. If for any reason the OTP is invalid, or the user needs another OTP.

This PR adds an endpoint that allows the user to request another OTP in an unauthenticated state. Regardless of secret verification the endpoint will always return 200 to protect against account enumeration.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-13 21:31 UTC, JaredSnider-Bitwarden requested changes

2024-12-13 21:31 UTC, JaredSnider-Bitwarden commented on test/Core.Test/Services/UserServiceTests.cs
Can we get complete test coverage for this new method?

2024-12-14 05:59 UTC, ike-kottlowski commented on test/Core.Test/Services/UserServiceTests.cs
Yep, added more explicit testing and some extra ones for `SendOTPAsync` in [d99e6f6](https://github.com/bitwarden/server/pull/5146/commits/d99e6f6b5aca3da3da3590d58acdd907062ed9b8)

2024-12-14 19:48 UTC, JaredSnider-Bitwarden commented on test/Core.Test/Services/UserServiceTests.cs
Thank you!

2024-12-14 19:48 UTC, JaredSnider-Bitwarden approved these changes

2024-12-16 15:57 UTC, merged