[PM-14381] Add POST /tasks/bulk-create endpoint
bitwarden/server pull request #5188
Opened 2024-12-23 23:42 UTC by gbubemismith

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-27 18:19 UTC, gbubemismith commented
This PR will be retargeted to main after https://github.com/bitwarden/server/pull/5039 merges.

2025-01-15 21:15 UTC, rkac-bw commented on src/Sql/dbo/User Defined Types/SecurityTaskType.sql
> +    [Id] UNIQUEIDENTIFIER NOT NULL,
We are trying to avoid custom data types that will need sql changes per schema changes.
The preference is to use the existing generic guidarray for bulk operations
CREATE TYPE [dbo].[GuidIdArray] AS TABLE(
	[Id] [uniqueidentifier] NOT NULL
)

2025-01-28 19:03 UTC, shane-melton requested changes
Looks good, nice work! Just some left over code I think we can clean up.

2025-01-28 20:15 UTC, shane-melton submitted a review, later dismissed
Looks good to go!!

2025-01-28 22:05 UTC, rkac-bw submitted a review, later dismissed
LGTM

2025-01-29 18:09 UTC, shane-melton commented on src/Core/Vault/Models/Api/SecurityTaskCreateRequest.cs
> +    [JsonConverter(typeof(JsonStringEnumConverter))]
⚠️ This now differs slightly from the request model in your [client PR](https://github.com/bitwarden/clients/pull/12891).

I think we can remove the `JsonConverter` and make the `CipherId` nullable?

2025-01-29 20:23 UTC, shane-melton approved these changes
Nice work!

2025-01-29 20:58 UTC, rkac-bw approved these changes
lgtm

2025-02-05 21:56 UTC, merged