Add userkey rotation v2
bitwarden/server pull request #5204
Opened 2024-12-31 21:42 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2025-01-16 00:39 UTC, JaredSnider-Bitwarden requested changes
This is an excellent change. Thank you for drastically improving our key rotation processes. I have just a few comments / questions below:

2025-01-16 00:39 UTC, JaredSnider-Bitwarden commented on src/Api/Auth/Controllers/AccountsController.cs
> +     * @deprecated
⚠️  We should use `[Obsolete("<message explaining deprecation + pointing to new endpoint>")]` to mark endpoints as deprecated like we do elsewhere.

2025-01-16 00:39 UTC, JaredSnider-Bitwarden commented on src/Core/KeyManagement/UserKey/Implementations/RotateUserAccountkeysCommand.cs
🎨 : I would highly recommend writing a test suite for this important command similar to the `RotateUserKeyCommandTests`

2025-01-16 00:39 UTC, JaredSnider-Bitwarden commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> -            await using (var cmd = new SqlCommand("[dbo].[User_UpdateKeys]", connection, transaction))
❓ : This looks like a good change to me, but there is a small bit of functionality difference where `User_UpdateKeys` used to make `AccountRevisionDate` default to `RevisionDate` if null. 

If that's not an issue, can you investigate what our proper stored proc deprecation processes are as I don't believe `User_UpdateKeys` is used anywhere else now?

2025-01-16 11:44 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> -            await using (var cmd = new SqlCommand("[dbo].[User_UpdateKeys]", connection, transaction))
Interesting, on the entityframework repository this does not have the same fallback behavior.

(Also, my changes just ignored the entity framework, so luckily caught that here).

2025-01-16 12:36 UTC, quexten commented on src/Core/KeyManagement/UserKey/Implementations/RotateUserAccountkeysCommand.cs
Added tests! Thanks for reminding me!

2025-01-21 22:05 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
Nice work! LGTM!

2025-01-22 14:36 UTC, quexten commented
Forgot to add the feature flag server-side; added it now.

2025-01-23 11:28 UTC, mzieniukbw requested changes

2025-01-23 11:28 UTC, mzieniukbw commented on util/Migrator/DbScripts_finalization/2025-01-21_UserkeyRotationV2.sql
> +IF OBJECT_ID('[dbo].[User_UpdateKeys]') IS NOT NULL
Do you wlaos want to delete this SP from repo ? Location: https://github.com/bitwarden/server/blob/7e74695afc4257a63b8dd280359277cd885cfc48/src/Sql/dbo/Stored%20Procedures/User_UpdateKeys.sql#L1

2025-01-27 12:17 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +            if (user.AccountRevisionDate == null)
:| I wonder why the SP had handling for this then:

https://github.com/bitwarden/server/blob/7e74695afc4257a63b8dd280359277cd885cfc48/src/Sql/dbo/Stored%20Procedures/User_UpdateKeys.sql#L20

2025-01-27 12:34 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +            await ReplaceAsync(user);
Replaced with:
```
            ProtectData(user);
            await connection.ExecuteAsync(
                $"[{Schema}].[{Table}_Update]",
                user,
                transaction: transaction,
                commandType: CommandType.StoredProcedure);

``` now

2025-01-28 11:27 UTC, quexten commented on src/Api/Auth/Controllers/AccountsController.cs
> +    public async Task PostUserAccountKeys([FromBody] RotateUserAccountKeysModel model)
Added unit tests and integration tests

2025-01-28 21:59 UTC, Thomas-Avery requested changes
Looking good, a few minor things to take a look at. 

An overall suggestion for net new code, can we use `#nullable enable` at the top of the files to enable nullable reference types? This is currently a mix of using that feature in some places and not in others, which I find confusing.

2025-01-28 21:59 UTC, Thomas-Avery commented on src/Infrastructure.EntityFramework/Repositories/UserRepository.cs
> +
```suggestion
            // Update user
            var userEntity = await dbContext.Users.FindAsync(user.Id);
            if (userEntity == null)
            {
                throw new ArgumentException("User not found", nameof(user));
            }

            userEntity.SecurityStamp = user.SecurityStamp;
            userEntity.Key = user.Key;
            userEntity.MasterPassword = user.MasterPassword;
            userEntity.PrivateKey = user.PrivateKey;
            userEntity.LastKeyRotationDate = user.LastKeyRotationDate;
            userEntity.AccountRevisionDate = user.AccountRevisionDate;
            userEntity.RevisionDate = user.RevisionDate;

            await dbContext.SaveChangesAsync();

            //  Update re-encrypted data
            foreach (var action in updateDataActions)
            {
                // connection and transaction aren't used in EF
                await action();
            }

            await transaction.CommitAsync();
        
```
:pick: Optional 

With the default behavior, you get rollbacks without having to do the try catch https://learn.microsoft.com/en-us/ef/core/saving/transactions#default-transaction-behavior

2025-01-28 21:59 UTC, Thomas-Avery commented on test/Api.Test/KeyManagement/Controllers/AccountsKeyManagementControllerTests.cs
> +
Would expect unit tests for failure cases. 

`_userService.GetUserByPrincipalAsync` returning null and throwing `UnauthorizedAccessException`.

`   var result = await _rotateUserAccountKeysCommand.RotateUserAccountKeysAsync(user, dataModel);` returning `result.Errors` and throwing `BadRequestException`

2025-01-28 21:59 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +                $"[{Schema}].[{Table}_Update]",
Seems odd to be doing a complete replacement of the user entity when this is called `UpdateUserKeyAndEncryptedDataV2Async`.  If anything changes on that user between the controller fetch and calling this repository method, we will overwrite it.

Can we do the following or is there something I'm missing?: 
```
            if (user.AccountRevisionDate == null)
            {
                user.AccountRevisionDate = user.RevisionDate;
            }
            
            // Update user values using data protection
            ProtectData(user);
            
              // Update user columns needed for key rotation
                   await connection.ExecuteAsync(
               $"[{Schema}].[User_UpdateKeys]",
               new
               {
                   user.Id,
                   user.SecurityStamp,
                   user.Key,
                   user.PrivateKey,
                   user.RevisionDate,
                   user.AccountRevisionDate,
                   user.LastKeyRotationDate
               },
               commandType: CommandType.StoredProcedure);

            //  Update re-encrypted data
            foreach (var action in updateDataActions)
            {
                await action(connection, transaction);
            }      
```

2025-01-28 21:59 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +        }
```suggestion
```

We don't need to `UnprotectData` the user entity because this method doesn't return anything.

2025-01-29 12:53 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +        }
The idea for this was that it is unclear if the caller expects the reference they pass in to be the same after calling. I guess since we are the only caller in rotateuseraccountkeyscommand, this should be safe. But it would be unexpected from a caller's point of view for the passed in user object to be mutated.

2025-01-29 13:02 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +                $"[{Schema}].[{Table}_Update]",
The above is missing at least the masterpassword hash and masterpassword hint. 

As it is implemented right now, we do our  sanity/safety checks regarding the: public key, email, kdf settings, before calling `UpdateUserKeyAndEncryptedDataV2Async`, with one user object that has been validated.

If we just update the above, it could be the case that f.e the kdf setting changes after the sanity check, but before the above update, leading to a key that does not match the kdf settings being stored. 

So we would either need to include:
public key, email, kdf settings, in the update too, replacing them?

2025-01-29 16:39 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +        }
In C# arguments are passed by value by default. You need to use the `ref` modifier to turn things into pass by reference.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters

Typically, for a repository layer, you have `Task` to indicate you will be saving the object as provided, or you return a value to indicate changes.

2025-01-29 16:54 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +                $"[{Schema}].[{Table}_Update]",
Looks like we're missing updating those fields in the EF code too then? 

I'm confused here.

2025-01-29 18:42 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +        }
This can be disregarded, followed up in slack.

2025-01-29 19:04 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +                $"[{Schema}].[{Table}_Update]",
Hmm, that means that the EF code is wrong. I think that means the EF code needs better test coverage in this case because this could have slipped through.

2025-01-29 19:17 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +                $"[{Schema}].[{Table}_Update]",
I know we recently published some new contributing docs info on EF integration tests. https://contributing.bitwarden.com/getting-started/server/database/ef/#testing-ef-changes

Might be something to look into here.

2025-01-30 14:06 UTC, quexten commented on test/Api.Test/KeyManagement/Controllers/AccountsKeyManagementControllerTests.cs
> +
Added!

2025-01-30 21:36 UTC, Thomas-Avery requested changes

2025-01-30 21:36 UTC, Thomas-Avery commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +        connection.Close();
Do we need the `connection.Close()` here?

I thought the using statements handle disposing and closing those things in dapper?

2025-01-30 21:36 UTC, Thomas-Avery commented on test/Core.Test/KeyManagement/UserKey/RotateUserAccountKeysCommandTests.cs
> +
```suggestion
  [Theory, BitAutoData]
    public async Task ThrowsWhenUserIsNull(SutProvider<RotateUserAccountKeysCommand> sutProvider,
        RotateUserAccountKeysData model)
    {
        await Assert.ThrowsAsync<ArgumentNullException>(async () => await sutProvider.Sut.RotateUserAccountKeysAsync(null, model));
    }
```

2025-01-31 11:23 UTC, quexten commented on src/Api/KeyManagement/Models/Requests/UserDataRequestModel.cs
> +    public required IEnumerable<SendWithIdRequestModel> Sends { get; set; }
That is my expectation, yes.

2025-01-31 16:35 UTC, Thomas-Avery requested changes
Looks good! Sorry, I missed checking these data validation attributes earlier.
Can we double-check these on the request models? I made some suggestions, looking at other request models.

After this I'm good to approve.

2025-01-31 16:35 UTC, Thomas-Avery commented on src/Api/Auth/Models/Request/Accounts/MasterPasswordUnlockDataModel.cs
> +    public required string MasterKeyEncryptedUserKey { get; set; }
```suggestion
    [EncryptedString] public required string MasterKeyEncryptedUserKey { get; set; }
```
Should some of these have the `[EncryptedString]` validator?

2025-01-31 16:35 UTC, Thomas-Avery commented on src/Api/KeyManagement/Models/Requests/AccountKeysRequestModel.cs
> +    public required string UserKeyEncryptedAccountPrivateKey { get; set; }
```suggestion
    [EncryptedString] public required string UserKeyEncryptedAccountPrivateKey { get; set; }
```

2025-01-31 16:35 UTC, Thomas-Avery commented on src/Api/Auth/Models/Request/Accounts/MasterPasswordUnlockDataModel.cs
> +    public required string Email { get; set; }
```suggestion
    [StrictEmailAddress]
    [StringLength(256)]
    public required string Email { get; set; }
```

2025-01-31 16:35 UTC, Thomas-Avery commented on src/Api/KeyManagement/Models/Requests/RotateAccountKeysAndDataRequestModel.cs
> +    public required string OldMasterKeyAuthenticationHash { get; set; }
```suggestion
    [StringLength(300)]
    public required string OldMasterKeyAuthenticationHash { get; set; }
```

2025-01-31 18:50 UTC, quexten commented
I believe I addressed all of the validation attributes (had to adjust some tests).

2025-01-31 19:16 UTC, Thomas-Avery submitted a review, later dismissed
LGTM, thank you!

2025-02-03 16:04 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2025-02-04 22:37 UTC, mzieniukbw approved these changes

2025-02-04 22:37 UTC, mzieniukbw commented on src/Core/KeyManagement/UserKey/Implementations/RotateUserAccountkeysCommand.cs
> +            return IdentityResult.Failed(_identityErrorDescriber.PasswordMismatch());
Exactly, simplify, by throwing error instead. On the client side, we do not do anything special, just display the error message, regardless of what it is.

2025-02-04 22:37 UTC, mzieniukbw commented on src/Core/KeyManagement/UserKey/Implementations/RotateUserAccountkeysCommand.cs
> +        user.LastKeyRotationDate = now;
🎨 I don't know which one is better, but feels weird right now:
```
        user.RevisionDate = now;
        user.AccountRevisionDate = now;
        user.LastKeyRotationDate = now;
```
or
```
user.RevisionDate = user.AccountRevisionDate = user.LastKeyRotationDate = now;
```

2025-02-04 22:37 UTC, mzieniukbw commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +            if (user.AccountRevisionDate == null)
Maybe some legacy reasons, probably was null, so we expect null ? Let's leave it.

2025-03-24 16:56 UTC, mzieniukbw requested changes

2025-03-24 16:56 UTC, mzieniukbw commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +            throw;
don't we have to explicitly rollback transaction before throwing ?

2025-03-25 10:18 UTC, quexten commented on src/Infrastructure.Dapper/Repositories/UserRepository.cs
> +            throw;
Added the rollback! Thank you for catching it.

2025-03-25 10:33 UTC, mzieniukbw approved these changes

2025-03-25 14:05 UTC, Thomas-Avery approved these changes

2025-03-25 14:23 UTC, merged